### ISSUE TITLE
Can't run tests - Cannot find module 'vscode'

### ISSUE THREAD

**Issue by tamj0rd2** [HackerFinn/vscode-todo#1]
How do you run the tests for this? What I've done:

1. Cloned the repo
2. Run `npm install` in the vscode-todo directory
3. Run `npm test`

Traceback:
```
> vscode-todo-renewed@0.8.5 test C:\Users\tamj0rd2\coding\vscode-todo
> mocha --recursive test/

module.js:471
    throw err;
    ^

Error: Cannot find module 'vscode'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\tamj0rd2\coding\vscode-todo\test\extension.test.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\tamj0rd2\coding\vscode-todo\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\tamj0rd2\coding\vscode-todo\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (C:\Users\tamj0rd2\coding\vscode-todo\node_modules\mocha\lib\mocha.js:469:10)
    at Object.<anonymous> (C:\Users\tamj0rd2\coding\vscode-todo\node_modules\mocha\bin\_mocha:404:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! Test failed.  See above for more details.
```

Running `npm ls` does show that `vscode` is installed.

**Comment by tamj0rd2** [comment]
Ignore this. It doesn't look like the tests are actually being used.
